# Generated by Django 4.1 on 2022-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
