# Generated by Django 4.1 on 2022-10-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pairingsession_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
                ('ownedBy', models.CharField(max_length=50)),
            ],
        ),
    ]
