# Generated by Django 4.1 on 2022-10-21 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pairinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
